### ISSUE TITLE
Use libspotify and pyspotify from apt.mopidy.com

### ISSUE THREAD

**Issue by jodal** [paulsturgess/mopidy-vagrant#1]
Mopidy, even the develop branch, will never depend on unreleased versions of pyspotify. Thus, you can simplify the recipe by using pyspotify and libspotify from apt.mopidy.com.

**Comment by paulsturgess** [comment]
OK thanks i'll take a look at that.

**Comment by paulsturgess** [comment]
The recipe is now updated to install python-spotify from apt.

The nice thing about that is there are no longer any version numbers specified. Well, except for gstreamer.
